const styleData = [
    {style: 'Golden Lager', srm: 6, ibu: 7, description: 'The golden lager has little in the way of hop and malt character. A straw to gold, very clean and crisp, highly carbonated lager.'},
    {stlye: 'Pilsner', srm: 7, ibu: 10, description: 'Quite possibly the most iconic beer style in modern history, the pilsner captured the attention of beer drinkers across the world and inspired a myriad of regional imitations. This lightly colored, exquisitely balanced lager remains one of the most loved beers to enjoy, and one of the most challenging for the brewer to create. Pilsner are characteristically light in color and have a very short finish. The world over, pilsner -style lagers have become the standard beer for many reasons, and American craft brewers have worked hard to put their own unique spin on this classic German beer.'},
    {style: 'Pale Ale', srm: 6, ibu: 12, description: 'Like many others that have become known as classic American beers, the American pale ale can trace its roots to beer styles from abroad. The American pale ale beer was inspired by the English pale ale, replacing its English counterpart’s earthy, herbal hops with generous additions of boldly citrus and pine-like American varieties. As one of the most popular American beer styles, pale ale beer is not hard to track down, but the various takes on this iconic style by just as many American craft brewers makes it impossible to jam everything there is to know about American pale ale beer on one page, but we’ll do our best.'},
    {style: 'India Pale Ale', srm: 8, ibu: 18, description: 'Characterized by floral, fruity, citrus-like, piney or resinous American-variety hop character, the IPA beer style is all about hop flavor, aroma and bitterness. This has been the most-entered category at the Great American Beer Festival for more than a decade, and is the top-selling craft beer style in supermarkets and liquor stores across the U.S.'},
    {style: 'Blonde Ale', srm: 6, ibu: 7, description: 'One of the most approachable styles, a golden or blonde ale is an easy-drinking beer that is visually appealing and has no particularly dominating malt or hop characteristics. Rounded and smooth, it is an American classic known for its simplicity. Sometimes referred to as “golden ale.” These beers can have honey, spices and fruit added, and may be fermented with lager or ale yeast.'},
    {style: 'Belgian-Style Dubbel', srm: 14, ibu: 8, description: 'The Belgian-style dubbel ranges from brown to very dark in color. They have a malty sweetness and can have cocoa and caramel aromas and flavors. Hop bitterness is medium-low to medium. Yeast-generated fruity esters (especially banana) can be apparent. Often bottle-conditioned, a slight yeast haze and flavor may be evident. “Dubbel” meaning “double,” this beer is still not so big in intensity as to surpass the Belgian-style quadrupel that is often considered its sibling.'},
    {style: 'Belgian-Style Tripel', srm: 7, ibu: 8, description: 'Complex, sometimes mild spicy flavor characterizes this style. Yeast-driven complexity is common. Tripels are often on the higher end of the ABV spectrum, yet are approachable to many different palates. These beers are commonly bottle-conditioned and finish dry. The Belgian-style tripel is similar to Belgian-style golden strong ales, but are generally darker and have a more noticeable malt sweetness.'},
    {style: 'Belgian-Style Quadrupel', srm: 12, ibu: 8, description: 'The Belgian-style Quadrupel is amber to dark brown in color. Caramel, dark sugar and malty sweet flavors dominate, with medium-low to medium-high hop bitterness. Quads have a relatively light body compared to their alcoholic strength. If aged, oxidative qualities should be mild and not distracting. Sometimes referred to as Belgian strong dark.'},
    {style: 'Light Sour Ale', srm: 8, ibu: 5, description: 'The acidity present in sour beer is usually in the form of lactic, acetic and other organic acids naturally developed with acidified malt in the mash, or produced during fermentation by the use of various microorganisms. These beers may derive their sour flavor from pure cultured forms of souring agents or from the influence of barrel aging.'},
    {style: 'Red Ale', srm: 14, ibu: 7, description: 'The Irish-style red ale is a balanced beer that uses a moderate amount of kilned malts and roasted barley in the recipe, which gives the beer the color for which it is named. Featuring an approachable hop bitterness which rests on the palate, this typically amber-colored beer is brewed as a lager or an ale, and can often have a medium, candy-like caramel malt sweetness. This style may contain adjuncts such as corn, rice, and sugar, which help dry out the beer’s finish and lessen the body. It also often contains roasted barley, lending low roasted notes, darker color and possible creation of a tan collar of foam on top. With notes of caramel, toffee and sometimes low-level diacetyl (butter), think of the Irish red ale beer style as a cousin to lightly-toasted and buttered bread.'},
    {style: 'Porter', srm: 17, ibu: 13, description: 'Definitively American, the imperial porter should have no roasted barley flavors or strong burnt/black malt character. Medium caramel and cocoa-like sweetness is present, with complementing hop character and malt-derived sweetness.'},
    {style: 'Dark Sour Ale', srm: 17, ibu: 5, description: 'The acidity present in sour beer is usually in the form of lactic, acetic and other organic acids naturally developed with acidified malt in the mash, or produced during fermentation by the use of various microorganisms. These beers may derive their sour flavor from pure cultured forms of souring agents or from the influence of barrel aging.'},
    {style: 'Brown Ale', srm: 18, ibu: 8, description: 'Roasted malt, caramel-like and chocolate-like characters should be of medium intensity in both flavor and aroma for the American brown ale. American-style brown ales have evident low to medium hop flavor and aroma and medium to high hop bitterness. The history of this style dates back to U.S. homebrewers who were inspired by English-style brown ales and porters. It sits in flavor between those British styles and is more bitter than both.'},
    {style: 'Stout', srm: 19, ibu: 13, description: 'American stout beer is perhaps one of the most identifiable creations of the American beer world. Stout beer is about as dark of an American beer as can be, and has a very noticeable of appearance, aroma and flavor. As one of the thicker, darker American beers on the craft beer scene, American stout beer is perfect for the colder seasons.'}
]

module.exports = styleData;